### ISSUE TITLE
兄弟 微软删除这个数据库了 你那儿有copy吗  给份链接呗 

### ISSUE THREAD

**Issue by Hsintao** [EB-Dodo/C-MS-Celeb#2]
RT

**Comment by ruochunjin** [comment]
有点遗憾。
由于项目已过两年，期间没有做好数据保管，原始的图像数据不慎遗失。
目前只剩下这个清单了。
我也是刚知道微软研究院将数据下架了。

**Comment by Hsintao** [comment]
好的，我已经找到一份清洗过的数据集，谢谢了 @PINTOFSTU

**Comment by elliottzheng** [comment]
@Hsintao 可以分享一下数据吗

**Comment by haofusheng** [comment]
@Hsintao 能分享下清洗过的数据吗？

**Comment by Hsintao** [comment]
insightface 的dataset-zoo有的 @haofusheng @elliottzheng

**Comment by elliottzheng** [comment]
好的，确实有，谢谢

--------------原始邮件--------------
发件人："Xintao "<notifications@github.com>;
发送时间：2019年6月10日(星期一) 下午5:13
收件人："PINTOFSTU/C-MS-Celeb" <C-MS-Celeb@noreply.github.com>;
抄送："Elliott Zheng "<admin@hypercube.top>;"Mention "<mention@noreply.github.com>;
主题：Re: [PINTOFSTU/C-MS-Celeb] 兄弟 微软删除这个数据库了 你那儿有copy吗  给份链接呗  (#2)
-----------------------------------

 
insightface 的dataset-zoo有的 @haofusheng @elliottzheng

**Comment by ruochunjin** [comment]
https://academictorrents.com/details/9e67eb7cc23c9417f39778a8e06cca5e26196a97/tech&hit=1&filelist=1
