### ISSUE TITLE
is that cleaned dataset??

### ISSUE THREAD

**Issue by iperov** [EB-Dodo/C-MS-Celeb#5]
I just downloaded recent 'whole dataset' you provided.
Looks like all faces are messed.

![slack_2019-11-24_20-12-14](https://user-images.githubusercontent.com/8076202/69497456-b9319700-0ef6-11ea-8ab7-a174475bc8eb.jpg)

**Comment by Hzzone** [comment]
Hi, @iperov, I wonder what software you use, can you help me? Thanks a lot!

**Comment by iperov** [comment]
@Hzzone software for what?

**Comment by Hzzone** [comment]
@iperov, the software to browse the images in your screenshot  🤗  🤗. I think it may be convenient for me to clean the dataset? Thanks a lot!

**Comment by iperov** [comment]
XnViewMP

**Comment by Hzzone** [comment]
Thanks a lot!

**Comment by ruochunjin** [comment]
> I just downloaded recent 'whole dataset' you provided.
> Looks like all faces are messed.
> 
> ![slack_2019-11-24_20-12-14](https://user-images.githubusercontent.com/8076202/69497456-b9319700-0ef6-11ea-8ab7-a174475bc8eb.jpg)

Oh this is interesting, look at these messy annotations! This seems to be a new challenge for the label cleaning work.
Honestly, I personally did not try the "whole dataset" torrent and I just posted it from someone's reply here.
