### ISSUE TITLE
Can you explain about other version of MS1M refine dataset?

### ISSUE THREAD

**Issue by PhanThanhTrung** [EB-Dodo/C-MS-Celeb#9]
Is there any document about XiangWu's Cleaned Dataset and MS-Celeb-1M WashList Cleaned Dataset? I saw those repo but I can't find any information about it. is XiangWu's Cleaned Dataset called MS1M IBUG?

**Comment by ruochunjin** [comment]
> Is there any document about XiangWu's Cleaned Dataset and MS-Celeb-1M WashList Cleaned Dataset? I saw those repo but I can't find any information about it. is XiangWu's Cleaned Dataset called MS1M IBUG?

Sorry that I do not know them quite well, since I also learned about their methods on their Github repos. I think you can post this question on their project pages for clearer explanations.
